export const ACTION_BOOKING_ADD_BOOKING = "booking/ACTION_BOOKING_ADD"
export const MUTATION_BOOKING_ADD = "booking/MUTATION_BOOKING_ADD"
export const ACTION_BOOKING_EDIT = "booking/ACTION_BOOKING_EDIT"
export const MUTATION_EDIT_BOOKING = "booking/MUTATION/EDIT_BOOKING"

export const ACTION_SET_MENU = "menu/ACTION_SET_MENU"
export const MUTATION_SET_MENU = "menu/MUTATION_SET_MENU"