export const ACTION_BOOKING_ADD = 'booking/ACTION_BOOKING_ADD'
export const MUTATION_BOOKING_ADD = 'booking/MUTATION_BOOKING_ADD'
export const ACTION_BOOKING_SAVE_TO_DB = 'booking/ACTION_BOOKING_SAVE_TO_DB'
export const MUTATION_BOOKING_SAVE_TO_DB = 'booking/MUTATION_BOOKING_SAVE_TO_DB'
export const ACTION_BOOKING_EDIT = 'booking/ACTION_BOOKING_EDIT'
export const MUTATION_BOOKING_EDIT = 'booking/MUTATION_BOOKING_EDIT'

export const ACTION_MENU_SET = 'menu/ACTION_MENU_SET'
export const MUTATION_MENU_SET = 'menu/MUTATION_MENU_SET'
